version: '3'

services:

  workspace:
    build:
      context: ${DOCKER_PATH}/workspace
      args:
        - PHP_DOCKERFILE_SOURCE=${PHP_DOCKERFILE_SOURCE}
    volumes:
      - ${APP_PATH}:/var/www
      - ${APP_PATH}/docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    tty: true
    networks:
      - network

  nginx:
    build:
      context: ${DOCKER_PATH}/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
    volumes:
      - ${APP_PATH}/docker/devops/sites:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
      - ${APP_PATH}:/var/www
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - network

  php-fpm:
    build:
      context: ${DOCKER_PATH}/php-fpm
      args:
        - PHP_FPM_DOCKERFILE_SOURCE=${PHP_FPM_DOCKERFILE_SOURCE}
        - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
    volumes:
      - ${APP_PATH}:/var/www
      - ${APP_PATH}/docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    expose:
      - ${PHP_UPSTREAM_PORT}
    networks:
      - network

networks:
  network:
    driver: ${NETWORKS_DRIVER}
